[package]
name = "rust-lua-demo"
version = "0.1.0"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"
unused = { level = "allow", priority = -1 }

[dependencies]
mlua = { version = "0.10", features = ["async", "lua54", "vendored", "send"] }
 
